name: LolNo
main: com.c45y.lolno.LolNo
version: 0.3
permissions:
    LolNo.mod:
        description: Chat while antispam shit is active
        default: op
    LolNo.admin:
        description: Turn on the antispam shit
        default: op
commands:
  lolno:
    description: Stop spam
    permission: lolno.admin
    usage: |
           /lolno: Toggle stop spam
  mutedlist:
    description: List muted players
    permission: lolno.mod
    usage: |
           /lolmute: Show a list of muted players
  mute:
    description: Mute players
    permission: lolno.mod
    usage: |
           /lolmute [player]: Mute a specific player
  unmute:
    description: Unmute players
    permission: lolno.mod
    usage: |
           /lolunmute [player]: Unmute a specific player
  denytp:
    description: Deny a player the ability to TP
    permission: lolno.mod
    usage: |
           /loldenytp [player]: Deny TP to a player
           