name: LolNo
main: com.c45y.LolNo.LolNo
version: 0.1
permissions:
    LolNo.mod:
        description: Chat while antispam shit is active
        default: op
    LolNo.admin:
        description: Turn on the antispam shit
        default: op
commands:
  lolno:
    description: Stop spam
    permission: LolNo.admin
    usage: |
           /lolno: Toggle stop spam
  lolmute:
    description: Mute players
    permission: LolNo.mod
    usage: |
           /lolmute [player]: Mute a specific player
  lolunmute:
    description: Unmute players
    permission: LolNo.mod
    usage: |
           /lolunmute [player]: Unmute a specific player